# Generated by Django 5.0.6 on 2024-07-12 01:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_delete_contact_alter_contactform_contact_form_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comunity_uuid', models.UUIDField(default=uuid.uuid4)),
                ('country', models.CharField(max_length=64)),
                ('comunity_name', models.CharField(max_length=100)),
            ],
        ),
    ]
