# Generated by Django 5.0.6 on 2024-07-12 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_comunity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flan',
            name='image',
            field=models.ImageField(null=True, upload_to='static/img'),
        ),
    ]
